-- ============================================================
-- RedditoAuto - Migration V1: Schema iniziale
-- Allineato esattamente allo schema generato da Hibernate 7
-- con CHECK constraints sugli enum e identity columns.
-- ============================================================

-- ========================
-- MARCA
-- ========================
CREATE TABLE IF NOT EXISTS marca (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT uq_marca_nome UNIQUE (nome)
);

-- ========================
-- MODELLO
-- ========================
CREATE TABLE IF NOT EXISTS modello (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anno_fine   INTEGER,
    anno_inizio INTEGER,
    nome        VARCHAR(100) NOT NULL,
    marca_id    BIGINT       NOT NULL,
    CONSTRAINT uq_modello UNIQUE (marca_id, nome, anno_inizio, anno_fine),
    CONSTRAINT fk_modello_marca FOREIGN KEY (marca_id) REFERENCES marca(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_modello_marca ON modello(marca_id);

-- ========================
-- MOTORIZZAZIONE
-- ========================
CREATE TABLE IF NOT EXISTS motorizzazione (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anno_produzione                 INTEGER         NOT NULL,
    autonomia_km_elettrica          INTEGER,
    cilindrata_cc                   INTEGER,
    confermato_manualmente          BOOLEAN         NOT NULL DEFAULT FALSE,
    consumo_extraurbano_litri_100km NUMERIC(5,2),
    consumo_medio_litri_100km       NUMERIC(5,2),
    consumo_urbano_litri_100km      NUMERIC(5,2),
    costo_tagliando_base_eur        NUMERIC(8,2),
    costo_tagliando_maior_eur       NUMERIC(8,2),
    data_estrazione                 TIMESTAMP(6),
    fonte_dati                      VARCHAR(500),
    gruppo_assicurativo             INTEGER,
    intervallo_tagliando_km         INTEGER,
    intervallo_tagliando_maior_km   INTEGER,
    misura_pneumatici_anteriori     VARCHAR(30),
    misura_pneumatici_posteriori    VARCHAR(30),
    nome_motore                     VARCHAR(150)    NOT NULL,
    potenza_cv                      INTEGER,
    potenza_kw                      INTEGER         NOT NULL,
    prezzo_listino_eur              NUMERIC(12,2),
    run_flat                        BOOLEAN         NOT NULL DEFAULT FALSE,
    tipo_cambio                     VARCHAR(30)
        CHECK (tipo_cambio IN ('MANUALE','AUTOMATICO_TRADIZIONALE','DCT','CVT','SINGOLA_MARCIA')),
    tipo_carburante                 VARCHAR(30)     NOT NULL
        CHECK (tipo_carburante IN ('BENZINA','DIESEL','GPL','METANO','IBRIDO_BENZINA','IBRIDO_DIESEL','IBRIDO_PLUGIN','ELETTRICO','IDROGENO')),
    modello_id                      BIGINT          NOT NULL,
    CONSTRAINT uq_motorizzazione UNIQUE (modello_id, nome_motore, anno_produzione),
    CONSTRAINT fk_motorizzazione_modello FOREIGN KEY (modello_id) REFERENCES modello(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_motorizzazione_modello    ON motorizzazione(modello_id);
CREATE INDEX IF NOT EXISTS idx_motorizzazione_carburante ON motorizzazione(tipo_carburante);
