CREATE TABLE marca
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT pk_marca PRIMARY KEY (id)
);

CREATE TABLE modello
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    marca_id    BIGINT       NOT NULL,
    nome        VARCHAR(100) NOT NULL,
    anno_inizio INTEGER,
    anno_fine   INTEGER,
    CONSTRAINT pk_modello PRIMARY KEY (id)
);

CREATE TABLE motorizzazione
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modello_id                      BIGINT       NOT NULL,
    nome_motore                     VARCHAR(150) NOT NULL,
    anno_produzione                 INTEGER      NOT NULL,
    tipo_carburante                 VARCHAR(30)  NOT NULL,
    tipo_cambio                     VARCHAR(30),
    potenza_kw                      INTEGER      NOT NULL,
    potenza_cv                      INTEGER,
    cilindrata_cc                   INTEGER,
    consumo_medio_litri_100km       DECIMAL(5, 2),
    consumo_urbano_litri_100km      DECIMAL(5, 2),
    consumo_extraurbano_litri_100km DECIMAL(5, 2),
    autonomia_km_elettrica          INTEGER,
    misura_pneumatici_anteriori     VARCHAR(30),
    misura_pneumatici_posteriori    VARCHAR(30),
    run_flat                        BOOLEAN      NOT NULL,
    prezzo_listino_eur              DECIMAL(12, 2),
    costo_tagliando_base_eur        DECIMAL(8, 2),
    costo_tagliando_maior_eur       DECIMAL(8, 2),
    intervallo_tagliando_km         INTEGER,
    intervallo_tagliando_maior_km   INTEGER,
    gruppo_assicurativo             INTEGER,
    fonte_dati                      VARCHAR(500),
    data_estrazione                 TIMESTAMP WITHOUT TIME ZONE,
    confermato_manualmente          BOOLEAN,
    CONSTRAINT pk_motorizzazione PRIMARY KEY (id)
);

ALTER TABLE modello
    ADD CONSTRAINT uc_ca7e4fb463063199c09f68373 UNIQUE (marca_id, nome, anno_inizio, anno_fine);

ALTER TABLE motorizzazione
    ADD CONSTRAINT uc_ff7f8997a7e464c3d2a6e0f8f UNIQUE (modello_id, nome_motore, anno_produzione);

ALTER TABLE marca
    ADD CONSTRAINT uc_marca_nome UNIQUE (nome);

ALTER TABLE modello
    ADD CONSTRAINT FK_MODELLO_ON_MARCA FOREIGN KEY (marca_id) REFERENCES marca (id);

ALTER TABLE motorizzazione
    ADD CONSTRAINT FK_MOTORIZZAZIONE_ON_MODELLO FOREIGN KEY (modello_id) REFERENCES modello (id);